### ISSUE TITLE
small typographical error

### ISSUE THREAD

**Issue by nmaxcom** [tomimick/chrome-ext-view-src#5]
Small thing but hurts a bit. You can just do a search&replace for `Hilight` to `Highlight` and be done with it :)

![image](https://user-images.githubusercontent.com/8936090/56095594-b8f00880-5ede-11e9-9345-45463831f5d3.png)

**Comment by tomimick** [comment]
Thanks for the info. Will fix it.

**Comment by nmaxcom** [comment]
No problem :)
