### ISSUE TITLE
I get an error, Access Denied

### ISSUE THREAD

**Issue by londonpete1958** [tomimick/chrome-ext-view-src#7]
Error: Access is denied to chrome:// and Chrome Store pages

Looks just what I need, but maybe out of date?

Regards
Pete

**Comment by tomimick** [comment]
Extension is still actively used. Please state what is the url where it fails. Note that local files and chrome: pages do not work because they are forbidden by the browser.

**Comment by londonpete1958** [comment]
I don't quite understand it, but after turning on the computer this morning, the extension now works. Maybe it needed a restart of Chrome, but it's working so this issue can be closed.

Many thanls
Pete
